### ISSUE TITLE
Dates for duration are exclusive

### ISSUE THREAD

**Issue by buksvdl** [countincognito/Zametek.ProjectPlan#51]
Start 1/6/2020 for duration of 15 renders finish 1/27/2020(Business Days) rather than 1/24/2020

**Comment by countincognito** [comment]
The dates are exclusive by design.

In your example January 24th (a Friday) is the final day of work. There is still work to be completed on that day and the work will not end until the day is over. So the work is not "finished" until the following work day, which is January 27th (a Monday)

The main reason for this was to create a clear distinction between zero-duration and one-day duration activities (something that never quite sat right with me in other tools).

For example, MS Project handles inclusive dates by essentially making the two activities them the same:

![ms_project](https://github.com/user-attachments/assets/89b14007-0752-4665-9bc3-14c08424b8cc)

Since zero-duration activities have special meaning in Project Plan, it tries to make the distinction more obvious:

![project_plan](https://github.com/user-attachments/assets/b5690c06-d01e-49c5-aa0a-2304e82d3cd8)

I hope this explains the logic behind it. Thanks for the input.

**Comment by buksvdl** [comment]
@countincognito, thanks for the explanation.
Would it at all be possible to make this configurable?
Why i ask, is that i tried to use the tool in last weeks PDMC but could not since my dates were totally different to the example project. 
While i understand your reasoning, i also took the Dummy for what it is, a point of indirection, inheriting the detail from its predecessor. 
What i find problematic is that a task that starts 00:01 on Monday, has 5 whole days to complete, cannot end 00:00 on Friday. I count 5 complete 24 hour periods here. The semantics around Dummy tasks is of no consequence here. What is, is the fact that 5 days work now has to take 6.
I am new to Project and this tool will be perfect for me since i am not planning to rely on my current employer for financing(MS-Project licenses in mind here) my upskilling in Project Design. On top of that i would rather support an effort to advance a tool based on the iDesign method.
I just wonder how one would use the current version? From my experience, how we consider start/end dates and duration, just doesn't fit the tool. Maybe other users can shed some light? I would greatly appreciate the input.

**Comment by countincognito** [comment]
Thanks for the feedback. I will see if it is possible to add this as a configuration setting.

**Comment by LarsKemmann** [comment]
This is working well in the v0.9.0-beta.1 release, for me at least. @buksvdl Does it work for you? If so I think this can be closed. 😊
![image](https://github.com/user-attachments/assets/d2519ff4-b727-4daf-b584-aad8a6969460)

**Comment by countincognito** [comment]
Now available in [v0.9.0](https://github.com/countincognito/Zametek.ProjectPlan/releases/tag/v0.9.0)
